sudo: required 
dist: trusty 
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_failure: always

env:
  matrix:
    - USE_DEB=true  
      ROS_DISTRO="indigo" 
      ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - USE_DEB=true  
      ROS_DISTRO="indigo" 
      ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu

script: 
  - source .ci_config/travis.sh
